2.5 Performance Assessment — Data Preprocessing - May 24, 2026 - lacaug0782

In [1]:
from datetime import datetime
from IPython.display import display, Markdown
todays_date = datetime.now().strftime("%Y-%m-%d")
student_id = "lacaug0782"

display(Markdown("# Data Preprocessing on Breast Cancer Dataset"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

# Data Preprocessing on Breast Cancer Dataset

### Date: 2026-05-25

### Student ID: lacaug0782

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

display(Markdown("## Step 2: Load and Explore Dataset"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

data = pd.read_csv("C:/Users/lacey/OneDrive/Documents/ECPI 2024/SDC485 AI_ML Data Analytics Methods_Modeling/2.5PA/breastCancerDataset.csv")
display(data.head())
print(data.info())
display(data.describe())

## Step 2: Load and Explore Dataset

### Date: 2026-05-25

### Student ID: lacaug0782

,ID,Diagnosis,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    object
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB
None

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

display(Markdown("## Step 3: Preprocess the Data"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

# Check missing values
print(data.isnull().sum())

# Fill missing numerical values with median
data = data.fillna(data.median(numeric_only=True))

# Remove duplicates
data = data.drop_duplicates()

print(f"Dataset shape after removing duplicates: {data.shape}")

# Standardize selected features
scaler = StandardScaler()

features_to_scale = ['concavity1', 'concavity3']

data[features_to_scale] = scaler.fit_transform(
    data[features_to_scale]
)

# Convert diagnosis labels to numbers
data['Diagnosis'] = data['Diagnosis'].map({
    'B': 0,
    'M': 1
})

# Define features and target
X = data.drop('Diagnosis', axis=1)
y = data['Diagnosis']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

print(f"Training samples: {X_train.shape[0]}")
print(f"Testing samples: {X_test.shape[0]}")

## Step 3: Preprocess the Data

### Date: 2026-05-25

### Student ID: lacaug0782

ID                    0
Diagnosis             0
radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
dtype: int64
Dataset shape after removing duplicates: (569, 32)
Training samples: 398
Testing samples: 171

In [4]:
from sklearn.svm import SVC

display(Markdown("## Step 4: Implement SVM"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

## Step 4: Implement SVM

### Date: 2026-05-25

### Student ID: lacaug0782

In [5]:
from sklearn.metrics import accuracy_score, classification_report
display(Markdown("## Step 5: Evaluate SVM Model"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

svm_accuracy = accuracy_score(y_test, y_pred_svm)
print(f"Accuracy Score: {svm_accuracy}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

## Step 5: Evaluate SVM Model

### Date: 2026-05-25

### Student ID: lacaug0782

Accuracy Score: 0.935672514619883

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       108
           1       0.95      0.87      0.91        63

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.94       171

In [6]:
from sklearn.model_selection import GridSearchCV

display(Markdown("## Step 6: GridSearchCV for SVM"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

param_grid = {
   'C': [0.1, 1, 10, 100],
   'kernel': ['linear', 'rbf', 'poly']
}
grid_search_svm = GridSearchCV(
   SVC(),
   param_grid,
   refit=True,
   verbose=2,
   cv=5
)
grid_search_svm.fit(X_train, y_train)
print("Best Parameters:")
print(grid_search_svm.best_params_)

## Step 6: GridSearchCV for SVM

### Date: 2026-05-25

### Student ID: lacaug0782

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END ...............................C=0.1, kernel=linear; total time=   0.2s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.1s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.3s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.0s
[CV] END ...............................C=0.1, kernel=linear; total time=   0.1s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END ..................................C=0.1, kernel=rbf; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=0.1, kernel=poly; total time=   0.0s
[CV] END .................................C=1, kernel=linear; total time=   1.8s
[CV] END .................................C=1, kernel=linear; total time=   0.9s
[CV] END .................................C=1, kernel=linear; total time=   3.8s
[CV] END .................................C=1, kernel=linear; total time=   1.3s
[CV] END .................................C=1, kernel=linear; total time=   2.4s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ....................................C=1, kernel=rbf; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ...................................C=1, kernel=poly; total time=   0.0s
[CV] END ................................C=10, kernel=linear; total time=   5.8s
[CV] END ................................C=10, kernel=linear; total time=   2.9s
[CV] END ................................C=10, kernel=linear; total time=   3.3s
[CV] END ................................C=10, kernel=linear; total time=   5.3s
[CV] END ................................C=10, kernel=linear; total time=   5.1s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ...................................C=10, kernel=rbf; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ..................................C=10, kernel=poly; total time=   0.0s
[CV] END ...............................C=100, kernel=linear; total time=  10.0s
[CV] END ...............................C=100, kernel=linear; total time=   7.0s
[CV] END ...............................C=100, kernel=linear; total time=  26.3s
[CV] END ...............................C=100, kernel=linear; total time=   7.9s
[CV] END ...............................C=100, kernel=linear; total time=  11.4s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END ..................................C=100, kernel=rbf; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
[CV] END .................................C=100, kernel=poly; total time=   0.0s
Best Parameters:
{'C': 1, 'kernel': 'linear'}

In [7]:
display(Markdown("## Step 7: Evaluate Tuned SVM"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

best_svm = grid_search_svm.best_estimator_
y_pred_tuned_svm = best_svm.predict(X_test)
tuned_accuracy = accuracy_score(y_test, y_pred_tuned_svm)

print(f"Accuracy Score: {tuned_accuracy}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_tuned_svm))

## Step 7: Evaluate Tuned SVM

### Date: 2026-05-25

### Student ID: lacaug0782

Accuracy Score: 0.9649122807017544

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       108
           1       0.93      0.98      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171

In [8]:
import xgboost as xgb

display(Markdown("## Step 8: Implement XGBoost"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

xgb_model = xgb.XGBClassifier(
use_label_encoder=False,
eval_metric='logloss'
)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

## Step 8: Implement XGBoost

### Date: 2026-05-25

### Student ID: lacaug0782

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [9]:
display(Markdown("## Step 9: Evaluate XGBoost"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print(f"Accuracy Score: {xgb_accuracy}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

## Step 9: Evaluate XGBoost

### Date: 2026-05-25

### Student ID: lacaug0782

Accuracy Score: 0.9766081871345029

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       108
           1       0.97      0.97      0.97        63

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

In [10]:
display(Markdown("## Step 10: GridSearchCV for XGBoost"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

param_grid_xgb = {
'n_estimators': [50, 100],
'learning_rate': [0.1, 0.2],
'max_depth': [3, 4]
}
grid_search_xgb = GridSearchCV(
 xgb.XGBClassifier(
    use_label_encoder=False,
    eval_metric='logloss'
),
   param_grid_xgb,
   refit=True,
   verbose=2,
   cv=5
)
grid_search_xgb.fit(X_train, y_train)

print("Best Parameters:")
print(grid_search_xgb.best_params_)

## Step 10: GridSearchCV for XGBoost

### Date: 2026-05-25

### Student ID: lacaug0782

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.1, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.1, max_depth=4, n_estimators=50; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.2s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.1, max_depth=4, n_estimators=100; total time=   0.2s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=3, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.0s
[CV] END ....learning_rate=0.2, max_depth=4, n_estimators=50; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.1s
[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END ...learning_rate=0.2, max_depth=4, n_estimators=100; total time=   0.1s

C:\Users\lacey\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:44:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best Parameters:
{'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100}

In [11]:
display(Markdown("## Step 11: Evaluate Tuned XGBoost"))
display(Markdown(f"### Date: {todays_date}"))
display(Markdown(f"### Student ID: {student_id}"))

best_xgb = grid_search_xgb.best_estimator_
y_pred_tuned_xgb = best_xgb.predict(X_test)
tuned_xgb_accuracy = accuracy_score(
    y_test,
    y_pred_tuned_xgb
)

print(f"Accuracy Score: {tuned_xgb_accuracy}")
print("\nClassification Report:")
print(classification_report(
y_test,
y_pred_tuned_xgb
))

## Step 11: Evaluate Tuned XGBoost

### Date: 2026-05-25

### Student ID: lacaug0782

Accuracy Score: 0.9649122807017544

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       108
           1       0.95      0.95      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171